### ISSUE TITLE
Final Image Upside Down

### ISSUE THREAD

**Issue by DineshHospeti** [benhylau/flying-photo-booth#42]
We would like to use this at a trade show.  Our device is fixed in portrait mode.  The final picture is displayed upside down.

**Comment by benhylau** [comment]
Which app is this? Party PhotoBooth only runs in landscape mode. Are you using Flying PhotoBooth?

**Comment by benhylau** [comment]
By the way, Dropbox and Facebook uploads are broken at the moment, due to API deprecations from the providers and I have not had time to update. I will be looking into these problems over the next few days. Please continue discussion on: https://github.com/groundupworks/flying-photo-booth

**Comment by DineshHospeti** [comment]
Party PhotoBooth.  Our device is forced to portrait mode.  The software works quite well in portrait mode, the final captured image is upside down.

**Comment by benhylau** [comment]
I can look into this later, but not until I have all the sharing features fixed, since those are impacting most users and are expected to work. So practically it would likely be Jan when I will look into this. When is the show?

**Comment by DineshHospeti** [comment]
Show is not until late February.

**Comment by benhylau** [comment]
See https://github.com/groundupworks/flying-photo-booth/issues/21
